---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-YKtHnj8R17kYM
  region: us-west-2

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  iam:
    withAddonPolicies:
      albIngress: true

secretsEncryption:
  keyARN: arn:aws:kms:us-west-2:878687028155:key/1cfbc727-37b6-4399-b3a6-5cecb7aadaf6
